<?php

namespace App\Models;

// use Illuminate\Contracts\AuthController\MustVerifyEmail;
use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;

class User extends Authenticatable
{
    /** @use HasFactory<UserFactory> */
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'userId',
        'name',
        'password',
    ];
    public $primaryKey = 'userId';
    public $incrementing = false;
    protected $keyType = 'string';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($query) {
            $query->userId = (string)Str::uuid();
        });
    }

    protected function casts(): array
    {
        return [
            'password' => 'hashed',
        ];
    }
    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */

    //RelationShips model

    public function posts(): HasMany
    {
        return $this->hasMany(Post::class, 'userId');
    }
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class, 'userId');
    }
    public function likes(): HasMany
    {
        return $this->hasMany(Like::class, 'userId');
    }

}
